### ISSUE TITLE
[Korekto][Daily] Votre note actuelle: 4.0/4

### ISSUE THREAD

**Issue by ledoyen** [TSHIBUNZIc/maven_training#1]
# Exercice commencé
Votre note est de **4.0**/4.

## Détail

* Part 1 - Git : 1.0
* Part 2 - CI : 1.0
* Part 3 - Coverage : 1.0
* Part 4 - Badges : 1.0

Analyse effectuée à 2021-03-15T00:13:11.801145400.

**Comment by TSHIBUNZIc** [comment]
![image](https://user-images.githubusercontent.com/65816066/110260523-f10a0400-7fac-11eb-92ea-348f7630685d.png)
Bonjour Monsieur je ne comprend pas trop pourtant mes commits sont bien dans la partie code?

**Comment by ledoyen** [comment]
Bonjour,

Oui vos commits sont listables dans l'onglet **_Code_** de GitHub.

Par ailleurs, la correction est claire:
* vous devriez avoir 7 commits avec les messages tels que définis dans le sujet
* vous n'en avez que 5
